### ISSUE TITLE
wrong form error styling when using form-control-label and/or form-control-feedback 

### ISSUE THREAD

**Issue by AkMaLiTo** [creativetimofficial/now-ui-kit#3]
Hello,
Upon adding a label with class form-control-label to any form field or using a div with form-control-feedback, the error styling gets all messed up...

to illustrate this issue please try changing the "Error Input" example in the index.html of your kit with the following:
```
<div class="col-sm-6 col-lg-3">
    <div class="form-group has-danger form-group-no-border">
        <label for="email" class="form-control-label">E-Mail Address</label>
        <input type="email" value="Error Input" class="form-control form-control-danger" />
        <div class="form-control-feedback">Error example</div>
    </div>
</div>
```

![2017-05-28_083417](https://cloud.githubusercontent.com/assets/29010851/26526595/79ddd760-4380-11e7-8654-17f459856bdd.png)

**Comment by alexandru-paduraru** [comment]
@AkMaLiTo thank you for pointing out. Please add this code in `assets/css/now-ui-kit.css` and we will add it in our next update too.

```css
// end of file
.form-group{
    position:relative;
}
.form-group.has-error, .form-group.has-danger{
    margin- bottom: 20px;
}

// line 1228
.has-success:after, .has-danger:after{
    right: 15px; //instead of 35
    bottom: 10px; // instead of top
}

// line 1213
.form-control + .form-control-feedback{
       border-radius: 0.25rem;
       font-size: 12px;
       margin-top: 0;
       position: absolute;
       left: 18px;
       bottom: -20px;
       vertical-align: middle;
}

```

Best,
Alex
