### ISSUE TITLE
Datepicker doesn't work

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/now-ui-kit#44]
For fixing this issue please go in your project in `assets/_scss/now-ui-kit/plugins/_plugin-datepicker.scss` and search for the following lines of code:

```css
.datepicker .day div,
.datepicker th {
  @include transition($general-transition-time, $transition-ease);
  text-align: center;
  width: 30px;
  height: 30px;
  line-height: 2.2;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 50%;
  font-weight: $font-weight-light;
  font-size: $font-size-base;
  border: none;
  position: relative;
  cursor: pointer;
}

```
Here you just have to add the property ‘ z-index: -1; ’ and after you do that please compile your scss with Koala( koala-app.com ). Please be sure that your output path is ‘ assets/css/now-ui-kit.css ‘. Everything will work fine after you will do the modification. Hope that will help you!

Regards,
Dragos
