### ISSUE TITLE
Problems with Date Picker

### ISSUE THREAD

**Issue by kelvindk9w** [creativetimofficial/now-ui-kit#71]
Hello, I am facing some problems with Datepicker that I can not solve (I have already looked at other topics here and nothing worked), it follows errors below:

1 - Arrows that select year / month do not work correctly, there is time that the return when being clicked advances the month forward.

2 - Selecting dates does not work. By clicking on the date, sometimes it goes, sometimes not, even giving several clicks, alternating the month the date selection does not work.

3 - if in value I put the date 06/03/2018 (d / m / Y), when I click to open the datepicker, instead of opening it in month 3, it is opening in other months, eg in June.

Even in the documentation site, when trying to use this function, I encounter difficulties and errors.

Other than that the theme is great, I'm getting to use it perfectly.

**Comment by dragosct10** [comment]
Hi, @kelvindk9w! Thank you for using our products. Yes, we must change that plugin with the datetimepicker in the next update because it causes multiple problems. To resolve the second issue please put on the:

```css
.table-condensed>tbody>tr>td, .table-condensed>tbody>tr>th, .table-condensed>tfoot>tr>td, .table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, .table-condensed>thead>tr>th{
     position: relative; 
     z-index: -1;
}
```

and on: 

```css
.datepicker .day div, .datepicker th{
   z-index: 1;
}
```

In this way you will fix the issue. 

Regards, 
Dragos
