### ISSUE TITLE
Wrong border-left custom color for .input-group-prepend

### ISSUE THREAD

**Issue by stebogit** [creativetimofficial/now-ui-kit#98]
I import the `nou-ui-kit.scss` files in order to customize my colors.
I noticed that on `input-group`s with `input-group-prepend` elements the left border is not correctly colored with my custom `$primary-color` (but the default orange):

```html
<div class="input-group">
    <div class="input-group-prepend">
        <span class="input-group-text">
            <i class="fa fa-user" aria-hidden="true"></i>
        </span>
    </div>
    <input id="email" type="text" class="form-control" name="email" required>
</div>
```
```scss
// now-ui-kit/scss/now-ui-kit/_inputs.scss

.input-group,
.form-group{
 // ...

  &.input-group-focus {
    .input-group-prepend .input-group-text {
      border-left: 1px solid #f96332; // <-- should be $primary-color
    }
    .input-group-append .input-group-text {
      border-right: 1px solid #f96332; // <-- should be $primary-color
    }
  }
}
```

![Screen Shot 2020-01-03 at 3 03 00 PM](https://user-images.githubusercontent.com/12717225/71754408-daad6900-2e3a-11ea-8eff-fdaf4082a933.png)

Using `$primary-color` in `_inputs.scss` fixes the issue.
